### ISSUE TITLE
Can't build from luarocks repository

### ISSUE THREAD

**Issue by gustavo-hms** [pocomane/luachild#3]
Hi!

Even though you don't mention that in the README, `luachild` [is present in LuaRocks repository](https://luarocks.org/modules/pocomane/luachild). But, if I try to build it running `luarocks install luachild`, I get the following error:
```
Installing https://luarocks.org/luachild-0.1-1.rockspec

Error: Directory v0.1 not found inside archive v0.1.tar.gz
```

It's handy to have it available on LuaRocks since we can make other modules depend on it.

**Comment by pocomane** [comment]
I updated the rocks on luarock.org to the last ones. Let me know if it works for you. (I made both the dev and the 0.1 rocks point to the github repo, so them both will always install the last version)

**Comment by gustavo-hms** [comment]
It works now. Thanks!
